defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: avalytics_development

test:
  <<: *defaults
  database: avalytics_test

# set these environment variables on your prod server
production:
  host: $OPENSHIFT_MONGODB_DB_HOST
  port: $OPENSHIFT_MONGODB_DB_PORT
  database: Avalytics
  username: admin
  password: i49cSCJrLgny
